= HOWTO: start service as docker container

== Environment preparations

[source,shell]
----
mkdir -p /logs
----

== Cleaning previosly started container

[source,shell]
----
docker ps -a # to determine if container is already running
docker kill vuzoll_explore_vk_data; docker rm vuzoll_explore_vk_data
----

== Configuration parameters

Following environment variable are avaiable for global service configuration:

EXPLORE_VK_MONGO_DATABASE_NAME - mongodb database name to use (default is vkIngested)

EXPLORE_VK_MONGO_AUTH_DATABASE_NAME - mongodb database name used for authentication (default is admin)

EXPLORE_VK_MONGO_HOST - host of mongodb instance (default is vuzoll_mongo)

EXPLORE_VK_MONGO_PORT - port of mongodb instance (default is 27017)

EXPLORE_VK_MONGO_USERNAME - username for authentication to mongodb (default is exploreVkService)

EXPLORE_VK_MONGO_PASSWORD - password for authentication to mongodb

EXPLORE_VK_ROOT_LOG_LEVEL - logging level for third-party libraries (default is INFO)

EXPLORE_VK_VUZOLL_LOG_LEVEL - logging level for service code (default is INFO)

== Start service

[source,shell]
----
docker pull vuzoll/vuzoll-explore-vk-data:$TAG # to load specific image
docker run -dit --name vuzoll_explore_vk_data --link vuzoll_mongo -v /logs:/logs -e EXPLORE_VK_MONGO_PASSWORD=MONGODB_PASSWORD -p 8081:8080 vuzoll/vuzoll-explore-vk-data:$TAG # to start specific image
----
